[package]
name = "zinput_device"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0.6"
serde = { version = "1.0.137", features = ["derive"] }
serde-big-array = "0.4.1"